### ISSUE TITLE
[Github] create tutorial on creating issues in github for non technical users of dApp, website, etc

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/docs#18]

**Comment by 42piratas** [comment]
I will take care of this one.

**Comment by 42piratas** [comment]
@pelsasser I created the PR https://github.com/MARKETProtocol/docs/pull/19 for a first review, but probably not the final version yet. I should have made some questions before starting, but - anyway - here they go now:

1 - Is it supposed to be a tutorial for reporting bugs, suggesting features, or both? (in my first version, I called it `Reporting Bugs`.
1 - Should we point non-tecnical users always to the same repo, since might not be so friendly ask them to open issues in the correct repo? If so, should we point them to?
1 - You'd like me to add anything else besides I've added in this first version?

**Comment by pelsasser** [comment]
@42piratas - thanks for the PR and attacking this issue!

The only existing information we have is currently this - https://docs.marketprotocol.io/#reporting-issues -
which does attempt to separate people into the correct repo.  

1. I think both.  Internal non technical team members definitely have alot of ideas and would love to have them be able to suggest them via github rather than directing them at a person and them getting lost
1. I think we can attempt to.  For instance, maybe there is a message somewhere in the dApp that asks for suggestion or issue reporting that is tied directly to the `dApp` repo.  Otherwise we can either create a `MARKET Improvement Proposal` or `MIP` repo perhaps for proposals.
1. Maybe a note that they need to create their own GH account in order to create an issue?

**Comment by 42piratas** [comment]
@pelsasser 

1. Would you have a suggestion for the section title (as it will appear on the left menu)? Or should I create two sections, one for reporting bugs and another one to suggesting features?
1. Yes, makes total sense when the user is using the dApp, then you forward them directly to the dApp repo. Now we just need to decide where we'll forward them when they are coming from the docs. 
1. Ofc, great point! 

I will update my changes and open a PR by the weekend. At first, I will point all users to the dApp repo, but later I can update accordingly if you get to a different conclusion.

**Comment by pelsasser** [comment]
I think "Bug Reporting" and "Feature Requests" would work as two separate but similar sections.  Pretty flexible on this to be honest.

What do you want to do with https://docs.marketprotocol.io/#reporting-issues ? remove it and put it under your new sectins?

**Comment by 42piratas** [comment]
To be honest, I don't have an idea/opinion for that. What's yours?

**Comment by 42piratas** [comment]
onn it

**Comment by 42piratas** [comment]
First part (reporting bugs): https://github.com/MARKETProtocol/docs/pull/20

**Comment by 42piratas** [comment]
Second part (feature requests): https://github.com/MARKETProtocol/docs/pull/21
