### ISSUE TITLE
update code style section

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/docs#8]
@eswarasai 

https://github.com/MARKETProtocol/docs/blob/master/source/includes/_contributing.md#coding-style

can you update per your preferences here?

**Comment by 42piratas** [comment]
@pelsasser If we will have 'coding style' per repo, I suggest we say exactly that on docs.marketprocol and explain how they can find the respective info in each repo instead of mentioning anything specific on docs.marketprotocol. Does it make sense? If you agree, pls let me know and I will update docs.marketprotocol.

**Comment by pelsasser** [comment]
yes please :+1:
